### ISSUE TITLE
exit(1) et sys.exit(1)

### ISSUE THREAD

**Issue by PiDroid-B** [PiDroid-B/example-python-fastfood#5]
JulienPalard :
`exit(1)` la builtin exit c'est surtout pour le repr, préfère `sys.exit(1)` dans une lib.

**Comment by PiDroid-B** [comment]
Je n'ai pas compris.
Après quelques recherche : sys_exit() correspont à la sortie du programme façon python alors que le exit() est la sortie façon shell. Est-ce bien cela ?
Ai-je raté une autre subtilité ?

**Comment by JulienPalard** [comment]
Pas tout à fait :
- `sys.exit()` est un fonction pour quitter Python.
- `exit` est une fonction native qui n'est là que pour que ce soit pratique de quitter un interpréteur interactif.

Demo :
```pycon
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
```

La bonne manière de quitter un script python est donc d'appeler `sys.exit()` qui est là pour ça, pas d'appeler la fonction native dont le seul but est d'aider les débutants à sortir de l'interpréteur interactif.

**Comment by PiDroid-B** [comment]
ah ok, j'ai pigé !
Merci

**Comment by PiDroid-B** [comment]
**Intégré au comit :** 71869f5
